services:
  mariadb:
    image: mariadb:10.3.29
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password123!
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/config/my.cnf:/etc/mysql/my.cnf:ro  # my.cnf 파일 마운트
      - ./mysql-encryption/keyfile:/etc/mysql/encryption/keyfile:ro  # 암호화 키 파일 마운트
    ports:
      - "3306:3306"
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  flask-app:
    build: ./flask-app
    container_name: flask-app
    restart: unless-stopped
    depends_on:
      - mariadb
      - mongodb
    environment:
      - DB_HOST=mariadb
      - DB_USER=flask_user
      - DB_PASSWORD=flask_password123!
      - DB_NAME=testdb
      - MONGO_HOST=mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local
